// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="axis_gemv_fixed_axis_gemv_fixed,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.091000,HLS_SYN_LAT=131341,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=439,HLS_SYN_LUT=521,HLS_VERSION=2024_1}" *)

module axis_gemv_fixed (
        ap_clk,
        ap_rst_n,
        strm_in_TDATA,
        strm_in_TVALID,
        strm_in_TREADY,
        strm_in_TKEEP,
        strm_in_TSTRB,
        strm_in_TLAST,
        strm_out_TDATA,
        strm_out_TVALID,
        strm_out_TREADY,
        strm_out_TKEEP,
        strm_out_TSTRB,
        strm_out_TLAST
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst_n;
input  [31:0] strm_in_TDATA;
input   strm_in_TVALID;
output   strm_in_TREADY;
input  [3:0] strm_in_TKEEP;
input  [3:0] strm_in_TSTRB;
input  [0:0] strm_in_TLAST;
output  [31:0] strm_out_TDATA;
output   strm_out_TVALID;
input   strm_out_TREADY;
output  [3:0] strm_out_TKEEP;
output  [3:0] strm_out_TSTRB;
output  [0:0] strm_out_TLAST;

 reg    ap_rst_n_inv;
reg   [8:0] localmem_address0;
reg    localmem_ce0;
reg    localmem_we0;
wire   [24:0] localmem_q0;
wire   [0:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_return;
reg   [0:0] targetBlock_reg_130;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
wire   [9:0] zext_ln28_fu_120_p1;
wire    ap_CS_fsm_state4;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_done;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_idle;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_ready;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_strm_in_TREADY;
wire   [8:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_i_out;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_i_out_ap_vld;
wire   [8:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_address0;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_ce0;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_we0;
wire   [24:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_d0;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_done;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_idle;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_ready;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TREADY;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_in_TREADY;
wire   [31:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TDATA;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID;
wire   [3:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TKEEP;
wire   [3:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TSTRB;
wire   [0:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TLAST;
wire   [8:0] grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_localmem_address0;
wire    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_localmem_ce0;
reg   [9:0] i_0260_reg_64;
reg    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [8:0] i_loc_fu_60;
reg    grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [6:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_strm_out_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state7;
wire    regslice_both_strm_in_V_data_V_U_apdone_blk;
wire   [31:0] strm_in_TDATA_int_regslice;
wire    strm_in_TVALID_int_regslice;
reg    strm_in_TREADY_int_regslice;
wire    regslice_both_strm_in_V_data_V_U_ack_in;
wire    regslice_both_strm_in_V_keep_V_U_apdone_blk;
wire   [3:0] strm_in_TKEEP_int_regslice;
wire    regslice_both_strm_in_V_keep_V_U_vld_out;
wire    regslice_both_strm_in_V_keep_V_U_ack_in;
wire    regslice_both_strm_in_V_strb_V_U_apdone_blk;
wire   [3:0] strm_in_TSTRB_int_regslice;
wire    regslice_both_strm_in_V_strb_V_U_vld_out;
wire    regslice_both_strm_in_V_strb_V_U_ack_in;
wire    regslice_both_strm_in_V_last_V_U_apdone_blk;
wire   [0:0] strm_in_TLAST_int_regslice;
wire    regslice_both_strm_in_V_last_V_U_vld_out;
wire    regslice_both_strm_in_V_last_V_U_ack_in;
wire    strm_out_TVALID_int_regslice;
wire    strm_out_TREADY_int_regslice;
wire    regslice_both_strm_out_V_data_V_U_vld_out;
wire    regslice_both_strm_out_V_keep_V_U_apdone_blk;
wire    regslice_both_strm_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_strm_out_V_keep_V_U_vld_out;
wire    regslice_both_strm_out_V_strb_V_U_apdone_blk;
wire    regslice_both_strm_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_strm_out_V_strb_V_U_vld_out;
wire    regslice_both_strm_out_V_last_V_U_apdone_blk;
wire    regslice_both_strm_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_strm_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start_reg = 1'b0;
#0 grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start_reg = 1'b0;
end

axis_gemv_fixed_localmem_RAM_AUTO_1R1W #(
    .DataWidth( 25 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
localmem_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(localmem_address0),
    .ce0(localmem_ce0),
    .we0(localmem_we0),
    .d0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_d0),
    .q0(localmem_q0)
);

axis_gemv_fixed_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1 grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start),
    .ap_done(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_done),
    .ap_idle(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_idle),
    .ap_ready(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_ready),
    .strm_in_TVALID(strm_in_TVALID_int_regslice),
    .strm_in_TDATA(strm_in_TDATA_int_regslice),
    .strm_in_TREADY(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_strm_in_TREADY),
    .strm_in_TKEEP(strm_in_TKEEP_int_regslice),
    .strm_in_TSTRB(strm_in_TSTRB_int_regslice),
    .strm_in_TLAST(strm_in_TLAST_int_regslice),
    .i_out(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_i_out),
    .i_out_ap_vld(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_i_out_ap_vld),
    .localmem_address0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_address0),
    .localmem_ce0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_ce0),
    .localmem_we0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_we0),
    .localmem_d0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_d0),
    .ap_return(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_return)
);

axis_gemv_fixed_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2 grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start),
    .ap_done(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_done),
    .ap_idle(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_idle),
    .ap_ready(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_ready),
    .strm_in_TVALID(strm_in_TVALID_int_regslice),
    .strm_out_TREADY(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TREADY),
    .strm_in_TDATA(strm_in_TDATA_int_regslice),
    .strm_in_TREADY(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_in_TREADY),
    .strm_in_TKEEP(strm_in_TKEEP_int_regslice),
    .strm_in_TSTRB(strm_in_TSTRB_int_regslice),
    .strm_in_TLAST(strm_in_TLAST_int_regslice),
    .strm_out_TDATA(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TDATA),
    .strm_out_TVALID(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID),
    .strm_out_TKEEP(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TKEEP),
    .strm_out_TSTRB(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TSTRB),
    .strm_out_TLAST(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TLAST),
    .i_0260(i_0260_reg_64),
    .localmem_address0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_localmem_address0),
    .localmem_ce0(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_localmem_ce0),
    .localmem_q0(localmem_q0)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 32 ))
regslice_both_strm_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TDATA),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_data_V_U_ack_in),
    .data_out(strm_in_TDATA_int_regslice),
    .vld_out(strm_in_TVALID_int_regslice),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_data_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TKEEP),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_keep_V_U_ack_in),
    .data_out(strm_in_TKEEP_int_regslice),
    .vld_out(regslice_both_strm_in_V_keep_V_U_vld_out),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_keep_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TSTRB),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_strb_V_U_ack_in),
    .data_out(strm_in_TSTRB_int_regslice),
    .vld_out(regslice_both_strm_in_V_strb_V_U_vld_out),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_strb_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_strm_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(strm_in_TLAST),
    .vld_in(strm_in_TVALID),
    .ack_in(regslice_both_strm_in_V_last_V_U_ack_in),
    .data_out(strm_in_TLAST_int_regslice),
    .vld_out(regslice_both_strm_in_V_last_V_U_vld_out),
    .ack_out(strm_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_strm_in_V_last_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 32 ))
regslice_both_strm_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TDATA),
    .vld_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID),
    .ack_in(strm_out_TREADY_int_regslice),
    .data_out(strm_out_TDATA),
    .vld_out(regslice_both_strm_out_V_data_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_data_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TKEEP),
    .vld_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID),
    .ack_in(regslice_both_strm_out_V_keep_V_U_ack_in_dummy),
    .data_out(strm_out_TKEEP),
    .vld_out(regslice_both_strm_out_V_keep_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_keep_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 4 ))
regslice_both_strm_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TSTRB),
    .vld_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID),
    .ack_in(regslice_both_strm_out_V_strb_V_U_ack_in_dummy),
    .data_out(strm_out_TSTRB),
    .vld_out(regslice_both_strm_out_V_strb_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_strb_V_U_apdone_blk)
);

axis_gemv_fixed_regslice_both #(
    .DataWidth( 1 ))
regslice_both_strm_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TLAST),
    .vld_in(grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID),
    .ack_in(regslice_both_strm_out_V_last_V_U_ack_in_dummy),
    .data_out(strm_out_TLAST),
    .vld_out(regslice_both_strm_out_V_last_V_U_vld_out),
    .ack_out(strm_out_TREADY),
    .apdone_blk(regslice_both_strm_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_ready == 1'b1)) begin
            grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start_reg <= 1'b1;
        end else if ((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_ready == 1'b1)) begin
            grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((targetBlock_reg_130 == 1'd1)) begin
            i_0260_reg_64 <= 10'd512;
        end else if ((targetBlock_reg_130 == 1'd0)) begin
            i_0260_reg_64 <= zext_ln28_fu_120_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_loc_fu_60 <= grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        targetBlock_reg_130 <= grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_return;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_strm_out_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        localmem_address0 = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_localmem_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        localmem_address0 = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_address0;
    end else begin
        localmem_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        localmem_ce0 = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_localmem_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        localmem_ce0 = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_ce0;
    end else begin
        localmem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        localmem_we0 = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_localmem_we0;
    end else begin
        localmem_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        strm_in_TREADY_int_regslice = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_in_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        strm_in_TREADY_int_regslice = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_strm_in_TREADY;
    end else begin
        strm_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_strm_out_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_25_1_fu_76_ap_start_reg;

assign grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_ap_start_reg;

assign grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TREADY = (strm_out_TREADY_int_regslice & ap_CS_fsm_state6);

assign strm_in_TREADY = regslice_both_strm_in_V_data_V_U_ack_in;

assign strm_out_TVALID = regslice_both_strm_out_V_data_V_U_vld_out;

assign strm_out_TVALID_int_regslice = grp_axis_gemv_fixed_Pipeline_VITIS_LOOP_32_2_fu_91_strm_out_TVALID;

assign zext_ln28_fu_120_p1 = i_loc_fu_60;

endmodule //axis_gemv_fixed
